version: 2.1
orbs: 
  github-cli: circleci/github-cli@2.1.0
jobs:
  checkout-repos:
    docker: 
      - image: cimg/base:stable
    steps:
      - checkout
      - github-cli/clone:
          repo: https://github.com/klsember/testing-cci
      - run: ls

workflows:
  test-checkouts:
    jobs:
      - checkout-repos

