version: 2.1

parameters:
  repository:
    type: string
    default: 'cci-dynamicconfig-demo'
  directory:
    type: string
    default: '$home/cci-dynamicconfig-demo'

jobs:
  checkout-repos:
    docker: 
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run: ls
      - run:
          name: Second Checkout
          command: |
            git clone clone git@github.com:${CIRCLE_PROJECT_USERNAME}/<<pipeline.parameters.repository>>.git <<pipeline.parameters.directory>>
      - run: ls

workflows:
  test-checkouts:
    jobs:
      - checkout-repos

