version: 2.1

parameters:
  repository:
    type: string
    default: 'cci-dynamicconfig-demo'

jobs:
  checkout-repos:
    docker: 
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run:
          name: Second Checkout
          command: |
            mkdir ${HOME}/<<pipeline.parameters.repository>>
            git clone git@github.com:${CIRCLE_PROJECT_USERNAME}/<<pipeline.parameters.repository>>.git ${HOME}/<<pipeline.parameters.repository>>
      - run:
          command: |
            cd $HOME
            ls

workflows:
  test-checkouts:
    jobs:
      - checkout-repos

