version: 2.1
orbs: 
  github-cli: circleci/github-cli@2.1.0
jobs:
  checkout-repos:
    docker: 
      - image: cimg/base:stable
    resource_class: small
    steps:
      - github-cli/setup
      - github-cli/clone
      - run: ls

workflows:
  test-checkouts:
    jobs:
      - checkout-repos

